name: tests

on:
  push:
  pull_request:

jobs:
  pester:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Tests on Windows PowerShell 5.1
        shell: powershell
        run: |
          Install-Module Pester -Force -Scope CurrentUser -SkipPublisherCheck -MinimumVersion 5.0
          Invoke-Pester -Path tests -CI

      - name: Tests on PowerShell 7
        shell: pwsh
        run: |
          Install-Module Pester -Force -Scope CurrentUser -SkipPublisherCheck -MinimumVersion 5.0
          Invoke-Pester -Path tests -CI
